# OWASP recommended defaults for Argon2id
argon2.memory=19456
argon2.iterations=2
argon2.parallelism=1
argon2.length=32
argon2.type=id
argon2.version=19
# Optional global pepper (not to be confused with a per-hash salt)
#The global.pepper is a defense-in-depth feature.\
#It adds a second, server-side secret to the password before hashing, creating an additional barrier if an attacker steals only your password database.
global.pepper=my-secret-pepper-key-change-this-in-production
# OWASP recommended defaults for bcrypt
# Weaker but somewhat fasten than Argon2
#bcrypt.rounds=12
#bcrypt.version=2b
# Added to get rid of the package warning
global.salt.length=64